wallpaper {
    monitor = eDP-1
    path = $HOME/Pictures/wallpaper.jpg
    fit_mode = cover
}
wallpaper {
    monitor = eDP-2
    path = $HOME/Pictures/wallpaper.jpg
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    path = $HOME/Pictures/wallpaper.jpg
    fit_mode = cover
}

